project:
  type: website
  output-dir: docs

website:
  title: "Polynomial Regression using RSV Data"
  sidebar:
    contents:
      - about.qmd
      - icon: github
        href: https://github.com/
    
format:
  html:
    theme: Solar
    css: styles.css
    code-fold: true
    code-tools: true

editor: visual

